### ISSUE TITLE
Units of Readings

### ISSUE THREAD

**Issue by ronakdedhia18** [MarkJB/python-pms7003#2]
Hi Mark,
I am getting this type of readings.

Date_Time | PM1 | PM2.5 | PM10
2019/02/14 09:52:35 | 260 | 2854 | 3936

Can you tell me what can be the unit of this readings?

Thank you.

**Comment by MarkJB** [comment]
Is that the output you are getting from my script?
The reason I ask is my script should print the units...

**Comment by ronakdedhia18** [comment]
Hi Mark,
![db1f5275-7392-4220-b0b9-ea01420b6b90](https://user-images.githubusercontent.com/14245201/52910744-075b9f00-32c2-11e9-8e2d-3487d4f12a95.jpg)
Attached the image of your script.
Please see to it

**Comment by ronakdedhia18** [comment]
Hi Mark,
What is difference between Pm1.0 reading and PM1 Atmospheric concentration?
For some other script i found on git hub i got this kind of output
Date_Time | PM1 | PM2.5 | PM10
2019/02/14 09:52:35 | 260 | 2854 | 3936

Please let me know difference between yours and this output and which one is efficient.

**Comment by MarkJB** [comment]
Looks like the sensor output isn't as expected.

My first thought is that isn't the output from a PMS7003 or the firmware has been changed along with the output.

I'll try it on my sensor when I get a chance just to make sure it still works for me.

**Comment by ronakdedhia18** [comment]
Please let me know as i am getting so much fluctuations in output from both the scripts and units of the output is also an problem.
Please let me know what can be done.
I am using Plant Tower PMS7003 sensor

**Comment by ronakdedhia18** [comment]
Hi Mark,
Also the range for 2.5 PM should be 0~500 ug/m3 as per data sheet but here its going upto 18176ug/m3.
Please let me know as soon as possible.

Thank you.

**Comment by MarkJB** [comment]
According to the datasheet, the standard measurements for "standard particle mass concentration value refers to the use of industrial metal particles as equivalent particles for density conversion"

> Hi Mark,
> What is difference between Pm1.0 reading and PM1 Atmospheric concentration?
> For some other script i found on git hub i got this kind of output
> Date_Time | PM1 | PM2.5 | PM10
> 2019/02/14 09:52:35 | 260 | 2854 | 3936
> 
> Please let me know difference between yours and this output and which one is efficient.
